"""
Django settings for pyconzim project.

Generated by 'django-admin startproject' using Django 2.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os
from wafer.settings import *
try:
    from localsettings import *
except ImportError:
    pass

from django.utils.translation import ugettext_lazy as _
from django.urls import reverse_lazy

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.abspath(__file__))



# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'e2o61*%#$%h^v=+-ery1tr2@x-!d!^s$yg1jfdg12vhh7$ecca'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


CRISPY_TEMPLATE_PACK = 'bootstrap4'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/
TEMPLATES[0]['DIRS'] = (
    os.path.join(BASE_DIR, 'templates'),
    ) + TEMPLATES[0]['DIRS']

STATICFILES_DIRS = (
        os.path.join(BASE_DIR, 'static'),)

STATIC_URL = '/static/'

WAFER_TALKS_OPEN = True
