"""
Django settings for pyconzim project.

Generated by 'django-admin startproject' using Django 2.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os
from wafer.settings import *
try:
    from localsettings import *
except ImportError:
    pass

from django.utils.translation import ugettext_lazy as _
from django.urls import reverse_lazy

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.abspath(__file__))



# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'e2o61*%#$%h^v=+-ery1tr2@x-!d!^s$yg1jfdg12vhh7$ecca'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


CRISPY_TEMPLATE_PACK = 'bootstrap4'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/
TEMPLATES[0]['DIRS'] = (
    os.path.join(BASE_DIR, 'templates'),
    ) + TEMPLATES[0]['DIRS']

# STATIC_ROOT = os.path.join(BASE_DIR, 'static')
STATICFILES_DIRS = (
        os.path.join(BASE_DIR, 'static'),)

STATIC_URL = '/static/'

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': 'pyconzim',
#         'USER': 'pyconzim',
#         'PASSWORD': 'pyconzim',
#         'HOST': 'db'
#     }
# }

WAFER_MENUS += (
    {"menu": "about", "label": _("About"),
     "items": [
         {"name": "young-coders", "label": _("Young Coders")}
         ]},
    {"name": "venue", "label": _("Venue"),
     "url": reverse_lazy("wafer_page", args=("venue",))},
    {"menu": "sponsors", "label": _("Sponsors"),
     "items": []},
    {"menu": "talks", "label": _("Talks"),
     "items": [
         #{"name": "schedule", "label": _("Schedule"),
         # "url": reverse_lazy("wafer_full_schedule")},
         {"name": "accepted-talks", "label": _("Accepted Talks"),
          "url": reverse_lazy("wafer_users_talks")},
         {"name": "speakers", "label": _("Speakers"),
          "url": reverse_lazy("wafer_talks_speakers")},
        ]},
    {"menu": "news", "label": _("News"),
     "items": []},
    # {"name": "twitter", "label": "Twitter",
    #  "image": "/static/img/twitter.png",
    #  "url": "https://twitter.com/pycon_zim"},
    # {"name": "googleplus", "label": "Google+",
    #  "image": "/static/img/googleplus.png",
    #  "url": "https://plus.google.com/114279924327039493110"},
    # {"name": "facebook", "label": "Facebook",
    #  "image": "/static/img/facebook.png",
    #  "url": "https://www.facebook.com/pyconzim"},
)

EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
WAFER_TALKS_OPEN = True
